#! /usr/bin/env bash

here=`pwd`


mkdir -p $here/libs/

cp `find . -type f -wholename "*.a"` ./libs

#generate a static library using all *.o generated by painless
ar -rv libs/libspots.a `find . -type f -wholename "*.o*"`
cd 

